swagger: "2.0"
info:
  description: 'This is the swagger spec for this Flask-API'
  version: '1.0.0'
  title: 'Flask-API'

consumes: 
  - 'application/json'
produces:
  - 'application/json'


paths:
  /createdb:
    get:
      operationId: app.create_db
      tags: 
        - db-helper
      summary: 'Creates a database per config settings'
      description: 'Creates a database per config settings'
      responses:
        '200':
          description: 'Creates a database per config settings' 

  /:
    get:

      operationId: app.welcome
      tags:
      - home
      summary: 'Retrives welcome message'
      description: 'Retrives welcome message'
      responses:
        '200':
          description: 'Welcome message'
          
  /health:
    get:
    
      operationId: app.health
      tags:
      - home
      summary: 'Retrieves health status of this application'
      description: 'Preforms health check of this api'
      responses:
        '200':
          description: 'Application functioning normally'

  /users/v1:
    get:
      operationId: app.get_users
      tags: 
        - users
      summary: 'Retrieves all user'
      description: 'Displays all users'
      responses:
        '200':
          description: 'See all users'