swagger: "2.0"
info:
  description: 'This is the swagger spec for this Flask-API'
  version: '1.0.0'
  title: 'Flask-API'

consumes: 
  - 'application/json'
produces:
  - 'application/json'


paths:
  /createdb:
    get:
      operationId: app.create_db
      tags: 
        - db-helper
      summary: 'Creates a database per config settings'
      description: 'Creates a database per config settings'
      responses:
        '200':
          description: 'Creates a database per config settings' 

  /:
    get:

      operationId: app.welcome
      tags:
      - home
      summary: 'Retrives welcome message'
      description: 'Retrives welcome message'
      responses:
        '200':
          description: 'Welcome message'
          
  /health:
    get:
    
      operationId: app.health
      tags:
      - home
      summary: 'Retrieves health status of this application'
      description: 'Preforms health check of this api'
      responses:
        '200':
          description: 'Application functioning normally'

  /users/v1:
    get:
      operationId: api.users.get_users
      tags: 
      - users
      summary: 'Retrieves all user'
      description: 'Displays all users'
      responses:
        '200':
          description: 'See all users'
    post:
      operationId: api.users.add_user
      tags: 
      - users
      summary: 'Creates a user'
      description: 'Creates a single user record'
      parameters:
        - name: user
          in: body
          description: 'Username to create'
          required: true
          schema:
            type: object
            properties:
              username: 
                type: string
              email:
                type: string 
      responses:
        '200':
          description: 'Successfully created user'
        '400':
          description: 'Invalid request'


  /users/v1/{username}:
    get:
      operationId: api.users.get_by_username
      tags:
      - users 
      summary: 'Retrieves user by username'
      description: 'Displays user by username'
      parameters:
        - name: username
          in: path
          description: 'Retrieves username data'
          type: string 
          required: true
      responses:
        '200':
          description: 'Successfully displayed user info'
          schema:
            type: array
            items:
              properties:
                username:
                  type: string
                email: 
                  type: string 
        '404':
          description: 'User not found'
    put:
      operationId: api.users.update_email
      tags:
      - users 
      summary: 'Updates user email'
      description: 'Updates a single user email'
      parameters:
        - name: username
          in: path
          description: 'Username to update email'
          type: string 
          required: true
        - name: user
          in: body
          description: 'field to update'
          required: true
          schema: 
            type: object
            properties: 
              email:
                type: string 
      responses:
        '204':
          description: 'Successfully updated user email'
        '400':
          description: 'Invalid request'
        '404':
          description: 'Username not found'
    delete:
      operationId: api.users.delete_user
      tags:
      - users
      summary: 'Deletes user data'
      description: 'Deletes user data by username'
      parameters:
        - name: username
          in: path
          description: 'Delete username'
          type: string
          required: true
      responses:
        '204':
          description: 'Successfully delete user'
        '404':
          description: 'Username not found'